export const projects = [
  {
    title: 'Covid-19 Status App',
    description: "COVID-19 Status is a free, open-source Android application that shows the current state of COVID-19 in India and the world. It has a beautiful, simple, fast, and responsive UI.",
    image: '/images/covid.jpg',
    tags: ['Java', 'XML', 'Firebase', 'Rest API'],
    source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: 'Portfolio Website',
    description: "This was my personal portfolio website that has all my work and project experience, including my resume. It used to be my main portfolio before deploying this current portfolio.",
    image: '/images/portfolio.jpg',
    tags: ['HTML', 'CSS', 'Bootstrap', 'JQuery'],
    source: 'https://github.com/lordarcadius/website',
    visit: 'https://project.vipuljha.com/website/',
    id: 1,
  },
  {
    title: 'ABS Tweaks',
    description: "ABS Tweaks or Arkaynine Boost Script is a collection of shell scripts written with the aim of enhancing the performance and battery life of an Android phone. It got 2 Lac+ downloads overall.",
    image: '/images/abs.jpg',
    tags: ['Shell', 'Busybox'],
    source: 'https://github.com/lordarcadius/ABS-Tweaks',
    visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    id: 2,
  },
  {
    title: 'ElectraBlue Kernel',
    description: "ElectraBlue is a flash & forget custom kernel for supported Android devices. It was developed with the aim to provide a stable, fluid, & battery-efficient experience with customizations.",
    image: '/images/eb.jpg',
    tags: ['Linux', 'C', 'Makefile', 'Bash'],
    source: 'https://github.com/lordarcadius/electrablue_mido',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  {
    title: 'Lenovo SNAPit',
    description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
    image: '/images/snapit.jpg',
    tags: ['Java', 'Libs', 'Smali'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 3,
  },
  {
    title: 'CyanogenOS Apps',
    description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
    image: '/images/capps.jpg',
    tags: ['Java', 'Libs'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a new developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  { year: 2021, text: 'Still trying to figure out this weird year.', },
];